apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: my-webhook
webhooks:
- name: validating-service.test.svc
  rules:
  - apiGroups:
    - ""
    - route.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - routes
    - pods
    - deployments
  clientConfig:
    service:
      namespace: test
      name: validating-service
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5UTXpPREEzTmpnNU1CNFhEVEU0TURndwpPVEE1TkRFeU9Gb1hEVEl6TURnd09EQTVOREV5T1Zvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFV6TXpnd056WTRPVENDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3E0R2pGeDR3aDR3Q29aQUdXNUt3Qyt4WWt6ejc3U1V3NGJOSktMVmlTRwpqdHhOOGhxNlJ2QURYUDlyNFhRRTdYcVRUOGFrSWpqaklMWC9YSkNBMi9sTXF4U2J6UHM3OEM0b2pWQ3lFSTdqCldTZHFrRGM3WFA5Q0dJQkU0M05iY2VsRUQ3WTBRMG9aWjhGZHlGNTNpa2FnOXZiaGlzZnU3eGVwRlY3dDNBNVEKWS8zY2xOemdxS0szZTQ2bTBlc1I5dlNNMjV6THhyRXBBdkNwMm82VW1HVmlGcFhkKzlZZHhRR0Zjckk0RTEzUgo1LytLQXFhdE9FSTQ3ZHppUlVaYjZ6RXpqanJodm5RQUVwclBUb1A4TjBIYnVMZTQ5bXU5WFpST3hvdVBKVUZwCmZDRzJCeStOdG1QWHdvZDlBellaREV0S3NqVVIzN2pIWWs0cnF5bk5Gd2NDQXdFQUFhTWpNQ0V3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdseApMcC9sSkdiMW1kSUgwYnNDNy9QNnBVOHB3ZHhMUlZPRDBnTU1FZ05HSnpxSnQvenJIU0RuVXJOanNxbVdvK1BpCk0xUFZIc1VOZzdvbHJvZ3NQWnE4SzFPWDk1QjVjTDZaQ2UzeGtTMm9VRmF4T0tmVi95SXduZ0I4Qk1yanZWb1IKVTdQTFdCWWc5V3pBNVlYbEh1ZU1xYjV5dWZwS2FwYlRaRHFTcEU3Ym9ENk9JUzBSN0tUNUJhSXAyY0NSbzJqTQpTSXNnM3doc0pzbEh5K0VUbjcrUXRsWlRNNHEzRnE3aTVjdW5OLzMyYmtLUmZYUG5qdkFzVHcyUGtKakU3bVZ0Ck5GZCtvSWxPVmJDRTBDclkvQW1Mb2k0UktEM1BTSWxQekp4S0tOQkJYeVRKL3hKTDhKNm1odDVnWVZHU0d2MWMKdWd3MUtPT1dWYjVZYXRhQitsUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
